version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"                # root of repo
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    # optionally: automerge minor/patch updates
    automerge: true
    automerge-type: "minor"
