name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy (manual approval)
    runs-on: ubuntu-latest
    environment:
      name: production    # this triggers the manual approval step

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy placeholder
        run: echo "🚀 Deploying application to production…"
