# .github/workflows/pr-check.yml
name: "PR only Status Check"
permissions:
  contents: read

on:
  pull_request:
    branches:
      - main

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run the app
        run: |
          python app.py

      - name: Show variable
        run: echo "API endpoint is ${{ vars.API_URL }}"